# -*- coding: utf-8 -*-

# blacklisted dns rrs
dns_blacklist = set(["gtld-servers.net",
"a.gtld-servers.net",
"b.gtld-servers.net",
"c.gtld-servers.net",
"d.gtld-servers.net",
"e.gtld-servers.net",
"f.gtld-servers.net",
"g.gtld-servers.net",
"h.gtld-servers.net",
"i.gtld-servers.net",
"j.gtld-servers.net",
"k.gtld-servers.net",
"l.gtld-servers.net",
"m.gtld-servers.net",
"root-servers.net",
"a.root-servers.net",
"b.root-servers.net",
"c.root-servers.net",
"d.root-servers.net",
"e.root-servers.net",
"f.root-servers.net",
"g.root-servers.net",
"h.root-servers.net",
"i.root-servers.net",
"j.root-servers.net",
"k.root-servers.net",
"l.root-servers.net",
"m.root-servers.net"])

# multi-resolver primary objects
mr_objectss = set(["SOA",
"NS",
"A",
"BGP-PREFIX",
"CC",
"AS",
"PTR"])

country_tld = {"Afghanistan": "AF", 
"Albania": "AL", 
"Algeria": "DZ", 
"American Samoa": "AS", 
"Andorra": "AD", 
"Angola": "AO", 
"Anguilla": "AI", 
"Antartica": "AQ", 
"Antigua and Barbuda": "AG", 
"Argentina": "AR", 
"Armenia": "AM", 
"Aruba": "AW", 
"Ascension Island": "AC", 
"Australia": "AU", 
"Austria": "AT", 
"Azerbaijan": "AZ", 
"Bahamas": "BS", 
"Bahrain": "BH", 
"Bangladesh": "BD", 
"Barbados": "BB", 
"Belarus": "BY", 
"Belgium": "BE", 
"Belize": "BZ", 
"Benin": "BJ", 
"Bermuda": "BM", 
"Bhutan": "BT", 
"Bolivia": "BO", 
"Bosnia and Herzegovina": "BA", 
"Botswana": "BW", 
"Bouvet Island": "BV", 
"Brazil": "BR", 
"British Indian Ocean Territory": "IO", 
"Brunei Darussalam": "BN", 
"Bulgaria": "BG", 
"Burkina Faso": "BF", 
"Burundi": "BI", 
"Cambodia": "KH", 
"Cameroon": "CM", 
"Canada": "CA", 
"Cap Verde": "CV", 
"Cayman Islands": "KY", 
"Central African Republic": "CF", 
"Chad": "TD", 
"Chile": "CL", 
"China": "CN", 
"Christmas Island": "CX", 
"Cocos (Keeling) Islands": "CC", 
"Colombia": "CO", 
"Comoros": "KM", 
"Congo, Democratic Republic of the": "CD", 
"Congo, Republic of": "CG", 
"Cook Islands": "CK", 
"Costa Rica": "CR", 
"Cote d'Ivoire": "CI", 
"Croatia/Hrvatska": "HR", 
"Cuba": "CU", 
"Cyprus": "CY", 
"Czech Republic": "CZ", 
"Denmark": "DK", 
"Djibouti": "DJ", 
"Dominica": "DM", 
"Dominican Republic": "DO", 
"East Timor": "TP", 
"Ecuador": "EC", 
"Egypt": "EG", 
"El Salvador": "SV", 
"Equatorial Guinea": "GQ", 
"Eritrea": "ER", 
"Estonia": "EE", 
"Ethiopia": "ET", 
"Falkland Islands (Malvina)": "FK", 
"Faroe Islands": "FO", 
"Fiji": "FJ", 
"Finland": "FI", 
"France": "FR", 
"French Guiana": "GF", 
"French Polynesia": "PF", 
"French Southern Territories": "TF", 
"Gabon": "GA", 
"Gambia": "GM", 
"Georgia": "GE", 
"Germany": "DE", 
"Ghana": "GH", 
"Gibraltar": "GI", 
"Greece": "GR", 
"Greenland": "GL", 
"Grenada": "GD", 
"Guadeloupe": "GP", 
"Guam": "GU", 
"Guatemala": "GT", 
"Guernsey": "GG", 
"Guinea": "GN", 
"Guinea-Bissau": "GW", 
"Guyana": "GY", 
"Haiti": "HT", 
"Heard and McDonald Islands": "HM", 
"Holy See (City Vatican State)": "VA", 
"Honduras": "HN", 
"Hong Kong": "HK", 
"Hungary": "HU", 
"Iceland": "IS", 
"India": "IN", 
"Indonesia": "ID", 
"Iran (Islamic Republic of)": "IR", 
"Iraq": "IQ", 
"Ireland": "IE", 
"Isle of Man": "IM", 
"Israel": "IL", 
"Italy": "IT", 
"Jamaica": "JM", 
"Japan": "JP", 
"Jersey": "JE", 
"Jordan": "JO", 
"Kazakhstan": "KZ", 
"Kenya": "KE", 
"Kiribati": "KI", 
"Korea, Democratic People's Republic": "KP", 
"Korea, Republic of": "KR", 
"Kuwait": "KW", 
"Kyrgyzstan": "KG", 
"Lao People's Democratic Republic": "LA", 
"Latvia": "LV", 
"Lebanon": "LB", 
"Lesotho": "LS", 
"Liberia": "LR", 
"Libyan Arab Jamahiriya": "LY", 
"Liechtenstein": "LI", 
"Lithuania": "LT", 
"Luxembourg": "LU", 
"Macau": "MO", 
"Macedonia, Former Yugoslav Republic": "MK", 
"Madagascar": "MG", 
"Malawi": "MW", 
"Malaysia": "MY", 
"Maldives": "MV", 
"Mali": "ML", 
"Malta": "MT", 
"Marshall Islands": "MH", 
"Martinique": "MQ", 
"Mauritania": "MR", 
"Mauritius": "MU", 
"Mayotte": "YT", 
"Mexico": "MX", 
"Micronesia, Federal State of": "FM", 
"Moldova, Republic of": "MD", 
"Monaco": "MC", 
"Mongolia": "MN", 
"Montserrat": "MS", 
"Morocco": "MA", 
"Mozambique": "MZ", 
"Myanmar": "MM", 
"Namibia": "NA", 
"Nauru": "NR", 
"Nepal": "NP", 
"Netherlands": "NL", 
"Netherlands Antilles": "AN", 
"New Caledonia": "NC", 
"New Zealand": "NZ", 
"Nicaragua": "NI", 
"Niger": "NE", 
"Nigeria": "NG", 
"Niue": "NU", 
"Norfolk Island": "NF", 
"Northern Mariana Islands": "MP", 
"Norway": "NO", 
"Oman": "OM", 
"Pakistan": "PK", 
"Palau": "PW", 
"Palestinian Territories": "PS", 
"Panama": "PA", 
"Papua New Guinea": "PG", 
"Paraguay": "PY", 
"Peru": "PE", 
"Philippines": "PH", 
"Pitcairn Island": "PN", 
"Poland": "PL", 
"Portugal": "PT", 
"Puerto Rico": "PR", 
"Qatar": "QA", 
"Reunion Island": "RE", 
"Romania": "RO", 
"Russian Federation": "RU", 
"Rwanda": "RW", 
"Saint Kitts and Nevis": "KN", 
"Saint Lucia": "LC", 
"Saint Vincent and the Grenadines": "VC", 
"San Marino": "SM", 
"Sao Tome and Principe": "ST", 
"Saudi Arabia": "SA", 
"Senegal": "SN", 
"Seychelles": "SC", 
"Sierra Leone": "SL", 
"Singapore": "SG", 
"Slovak Republic": "SK", 
"Slovenia": "SI", 
"Solomon Islands": "SB", 
"Somalia": "SO", 
"South Africa": "ZA", 
"South Georgia and the South Sandwich Islands": "GS", 
"Spain": "ES", 
"Sri Lanka": "LK", 
"St. Helena": "SH", 
"St. Pierre and Miquelon": "PM", 
"Sudan": "SD", 
"Suriname": "SR", 
"Svalbard and Jan Mayen Islands": "SJ", 
"Swaziland": "SZ", 
"Sweden": "SE", 
"Switzerland": "CH", 
"Syrian Arab Republic": "SY", 
"Taiwan": "TW", 
"Tajikistan": "TJ", 
"Tanzania": "TZ", 
"Thailand": "TH", 
"Togo": "TG", 
"Tokelau": "TK", 
"Tonga": "TO", 
"Trinidad and Tobago": "TT", 
"Tunisia": "TN", 
"Turkey": "TR", 
"Turkmenistan": "TM", 
"Turks and Caicos Islands": "TC", 
"Tuvalu": "TV", 
"US Minor Outlying Islands": "UM", 
"Uganda": "UG", 
"Ukraine": "UA", 
"United Arab Emirates": "AE", 
"United Kingdom": "UK", 
"United States": "US", 
"Uruguay": "UY", 
"Uzbekistan": "UZ", 
"Vanuatu": "VU", 
"Venezuela": "VE", 
"Vietnam": "VN", 
"Virgin Islands (British)": "VG", 
"Virgin Islands (USA)": "VI", 
"Wallis and Futuna Islands": "WF", 
"Western Sahara": "EH", 
"Western Samoa": "WS", 
"Yemen": "YE", 
"Yugoslavia": "YU", 
"Zambia": "ZM", 
"Zimbabwe": "ZW"}

http_user_agents = ["Mozilla/1.22 (compatible; MSIE 2.0d; Windows NT)", 
"Mozilla/1.22 (compatible; MSIE 2.0; Windows 95)", 
"Mozilla/2.0 (compatible; MSIE 3.02; Windows CE; 240x320)", 
"Mozilla/2.0 (compatible; MSIE 3.0; Windows 3.1)", 
"Mozilla/4.0 (compatible; MSIE 4.01; Digital AlphaServer 1000A 4/233; Windows", 
"Mozilla/4.0 (compatible; MSIE 4.01; Windows NT 5.0)", 
"Mozilla/4.0 (compatible; MSIE 5.01; Windows 95; MSIECrawler)", 
"Mozilla/4.0 (compatible; MSIE 5.01; Windows 98; Config C)", 
"Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0; .NET CLR 1.1.4322; .NET", 
"Mozilla/4.0 (compatible; MSIE 5.0; Windows 2000) Opera 6.0 [en]", 
"Mozilla/4.0 (compatible; MSIE 5.0; Windows 3.1)", 
"Mozilla/4.0 (compatible; MSIE 5.0; Windows 95) Opera 6.01 [en]", 
"Mozilla/4.0 (compatible; MSIE 5.0; Windows NT; DigExt)", 
"Mozilla/4.0 (compatible; MSIE 5.5; Windows 95)", 
"Mozilla/4.0 (compatible; MSIE 5.5; Windows 95; BCD2000)", 
"Mozilla/4.0 (compatible; MSIE 5.5; Windows 98)", 
"Mozilla/4.0 (compatible; MSIE 5.5; Windows NT 4.0)", 
"Mozilla/4.0+(compatible;+MSIE+5.5;+Windows+NT+4.0;+H010818)", 
"Mozilla/4.0 (compatible; MSIE 5.5; Windows NT 4.0; .NET CLR 1.0.2914)", 
"Mozilla/4.0 (compatible; MSIE 5.5; Windows NT 5.0)", 
"Mozilla/4.0 (compatible; MSIE 5.5; Windows NT 5.0; .NET CLR 1.1.4322)", 
"Mozilla/4.0 (compatible; MSIE 5.5; Windows NT 5.0; T312461)", 
"Mozilla/4.0 (compatible; MSIE 5.5; Windows NT 5.0; TIMET-0904;", 
"Mozilla/4.0 (compatible; MSIE 5.5; Windows NT 5.1; .NET CLR 1.1.4322; .NET", 
"Mozilla/4.0 (compatible; MSIE 6.0; AOL 9.0; Windows NT 5.1)", 
"Mozilla/4.0 (compatible; MSIE 6.0; MSIE 5.5; Windows NT 4.0) Opera 7.0 [en]", 
"Mozilla/4.0 (compatible; MSIE 6.0; MSIE 5.5; Windows NT 5.0) Opera 7.02", 
"Mozilla/4.0 (compatible; MSIE 6.0; Update a; AOL 6.0; Windows 98)", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows 98; Win 9x 4.90)", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows 98; Win 9x 4.90; Creative)", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows CE; PPC; 480x640) Opera 8.60 [en]", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows ME) Opera 7.11 [en]", 
"Mozilla/4.0      (compatible;      MSIE      6.0;      Windows     NT)", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0)", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0;", 
"Mozilla/4.0+(compatible;+MSIE+6.0;+Windows+NT+5.0;+", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; APC; .NET CLR 1.0.3705;", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; AT&T CSM7.0;", 
"Mozilla/4.0  (compatible;  MSIE  6.0;  Windows  NT  5.0; Avant Browser", 
"Mozilla/4.0  (compatible;  MSIE  6.0;  Windows NT 5.0; Google Wireless", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; KTXN)", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; .NET CLR 1.0.3705;", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; .NET CLR 1.0.3705; .NET", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; T312461)", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; Avant Browser;", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; BT [build 60A];", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; Crazy Browser 1.0.5)", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; Deepnet Explorer 1.5.0;", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; DIL0001021)", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; en) Opera 8.00", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; en) Opera 9.0", 
"Mozilla/4.0  (compatible; MSIE 6.0; Windows NT 5.1; FREE; .NET CLR", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; FREE; .NET CLR 1.1.4322)", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; iebar)", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; i-NavFourF;", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; KKman2.0)", 
"Mozilla/4.0  (compatible;  MSIE 6.0; Windows NT 5.1; Maxthon; .NET CLR", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; MyIE2; Deepnet Explorer)", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; .NET CLR 1.0.3705)", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; .NET CLR 1.1.4322)", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; .NET CLR 1.1.4322; Alexa", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; .NET CLR 1.1.4322; FDM)", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1) Netscape/8.0.4", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; Q312461)", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1;", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; Crazy Browser 2.0.0", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; FunWebProducts; .NET", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; Media Center PC", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; NeosBrowser; .NET", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.0.3705;", 
"Mozilla/4.0 (compatible- MSIE 6.0- Windows NT 5.1- SV1- .NET CLR 1.1.4322", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322;", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322)", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; YPC 3.0.2; .NET CLR", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; TheFreeDictionary.com;", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; SV1; .NET CLR 1.1.4322;", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; Win64; AMD64)", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; Win64; x64; SV1; .NET CLR", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; WOW64; SV1; .NET CLR", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows XP)", 
"Mozilla/4.0 (compatible; MSIE 7.0b; Windows NT 6.0)", 
"Mozilla/4.0 (compatible; MSIE 7.0b; Windows NT 6.0 ; .NET CLR 2.0.50215; SL", 
"Mozilla/4.0  (compatible;  MSIE  7.0; Windows NT 5.1; DOF-IE; .NET CLR", 
"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; .NET CLR 1.1.4322; IEMB3; IE", 
"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; .NET CLR 1.1.4322; .NET", 
"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; SV1; Maxthon; .NET CLR", 
"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727)", 
"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.2; Win64; x64; .NET CLR", 
"Mozilla/4.0  (compatible;  MSIE  7.0;  Windows NT 5.2; WOW64; .NET CLR", 
"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0; SLCC1; .NET CLR", 
"Mozilla/6.0 (compatible; MSIE 7.0a1; Windows NT 5.2; SV1)"]

