=head1 NAME

B<opencollab-agent> - OpenCollab agent.

=head1 SYNOPSIS

B<opencollab-agent> <options> <arguments>

=head1 SUMMARY

B<opencollab-agent> OpenCollab agent technology.

=head1 OPTIONS

=over 8

=item B<-c CONFIG --config=CONFIG> 

Path to opencollab configuration file, e.g. /etc/opencollab/opencollab.conf.

=item B<-h --help> 

Display the help message and exit.

=item B<-n NAME --name=NAME> 

Agent NAME.

=item B<-u URL --url=URL> 

Collab URL.

=item B<-U USERNAME --username=USERNAME> 

Collab USERNAME.

=item B<-v --verbose> 

Print verbose output to STDOUT.

=back

=head1 FILES

=over 8

=item B</etc/opencollab/opencollab.conf>

The default configuration file.

=back

=head1 SEE ALSO

=over 8

=item python(1)

=back

=head1 BUGS

Bug reports, patches and feature wishes should reported at http://graphingwiki.webfactional.com/ 

=cut
