=head1 NAME

B<opencollab-delete-pages> - Delete pages from a collab.

=head1 SYNOPSIS

B<opencollab-delete-pages> <options> <arguments>

=head1 SUMMARY

B<opencollab-delete-pages> Delete pages from a collab with MetaTable() arguments.

=head1 OPTIONS

=over 8

=item B<-c CONFIG --config=CONFIG> 

Path to opencollab configuration file, e.g. /etc/opencollab/opencollab.conf.

=item B<-h --help> 

Display the help message and exit.

=item B<-n, --dry-run>

Show what would have been deleted.

=item B<-s SEARCH-STRING, --search-string=SEARCH-STRING>

MetaTable() SEARCH-STRING.

=item B<-u URL --url=URL> 

Collab URL.

=item B<-U USERNAME --url=USERNAME> 

Collab USERNAME.

=item B<-v --verbose> 

Print verbose output to STDOUT.

=back

=head1 FILES

=over 8

=item B</etc/opencollab/opencollab.conf>

The default configuration file.

=back

=head1 SEE ALSO

=over 8

=item python(1)

=back

=head1 BUGS

Bug reports, patches and feature wishes should reported at http://graphingwiki.webfactional.com/ 

=cut
