=head1 NAME

B<opencollab-codetools-uploader> - Upload Codenomicon tools to a collab.

=head1 SYNOPSIS

B<opencollab-codetools-uploader> [options]

=head1 SUMMARY

B<opencollab-codetools-uploader> - Upload Codenomicon tools to a collab for a given user.

=head1 OPTIONS

=over 8

=item B<-a ARENA-DIR-GLOB --arena-dir-glob=ARENA-DIR-GLOB> 

ARENA-DIR-GLOB, i.e. "/path/to/arena/*/*/.htaccess"

=item B<-c CONFIG --config=CONFIG> 

Path to opencollab configuration file, e.g. /etc/opencollab/opencollab.conf.

=item B<-e ARENA-USER --arena-dir-glob=ARENA-USER> 

ARENA-USER, i.e. foo.bar@example.invalid

=item B<-h --help> 

Display the help message and exit.

=item B<-m MARKER --marker=MARKER> 

MARKER meta key to remove if tool has changed.

=item B<-t TEMPLATE --template=TEMPLATE> 

Collab TEMPLATE to use.

=item B<-u URL --url=URL> 

Collab URL.

=item B<-U USERNAME --username=USERNAME> 

Collab USERNAME.

=item B<-v --verbose> 

Print verbose output to STDOUT.

=back

=head1 ARGUMENTS

=over 8

=item B<arg> 

Argument

=back

=head1 FILES

=over 8

=item B</etc/opencollab/opencollab.conf>

The default configuration file.

=back

=head1 SEE ALSO

=over 8

=item python(1)

=back

=head1 BUGS

Bug reports, patches and feature wishes should reported at http://graphingwiki.webfactional.com/ 

=cut
