#!/bin/sh
SVNREVISION=`svn info | awk '/Revision/ {print $2}'`
DATE=`date +%Y%m%d`
MYDIR=`basename $PWD`
PACKAGE=/tmp/graphingwiki-svn$SVNREVISION.tar.bz2
sed "s/SVNREVISION/$SVNREVISION/;s/BUILDDATE/$DATE/;s/MYDIR/$MYDIR/" < graphingwiki.spec.in > graphingwiki.spec
(cd ..; tar cvjf $PACKAGE $MYDIR)
rpmbuild -ta $PACKAGE


 


