#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
    @copyright: 2008 by Joachim Viide, Pekka Pietikäinen, Mika Seppänen  
    @license: MIT <http://www.opensource.org/licenses/mit-license.php>
"""
from opencollab.wiki import CLIWiki
from opencollab.meta import Meta
from opencollab.util.config import parseConfig
import os
import sys
import optparse
import ConfigParser
from urllib import quote

def uploadFile(wiki, page, filename, path):
    file = open(path, "rb")

    for current, total in wiki.putAttachmentChunked(page, filename, file):
        percent = 100.0 * current / float(max(total, 1))
        status = current, total, percent

        sys.stdout.write("\rsent %d/%d bytes (%.02f%%) " % status)
        sys.stdout.flush()

    sys.stdout.write("done\n")
    sys.stdout.flush()

    file.close()

def main():
    parser = optparse.OptionParser()
    parser.add_option( "-c", "--config",
                      action="store",
                      type="string", dest="config",
                      metavar="CONFIG",
                      help="CONFIG file path.")
    parser.add_option("-p", "--page",
                      dest="page",
                      default=None,
                      metavar="PAGE",
                      help="Upload the file(s) to PAGE.")
    parser.add_option("-u", "--url",
                      dest="url",
                      default=None,
                      metavar="COLLAB-URL",
                      help="COLLAB-URL to connect to.")
    parser.set_usage("%prog [options] 0..N optional input directories")
    options, args = parser.parse_args()
    iopts={}
    ilist=[]
    if options.config:
        iopts = parseConfig(options.config, "creds", "uploader")
    if len(args) > 0:
        for arg in args:
            ilist.append(arg)
    elif options.config and "path" in iopts["uploader"]:
        ilist = (iopts["uploader"]["path"])
    else:
        parser.error("You need to specify 1..N positional input directories. Use -h for help.")
    if options.page:
        page = options.page
    elif options.config and "page" in iopts["uploader"]:
        page = iopts["uploader"]["page"]
    else:
        parser.error("Collab page to upload to needs to be specified. Use -h for help.")
    if options.url:
        url = options.url
        collab = CLIWiki(url)
    elif options.config and "url" in iopts["creds"]:
        url = iopts["creds"]["url"]
        collab = CLIWiki(url, config=options.config)
    else:
        parser.error("Collab URL needs to specified. Use -h for help.")

    filelist = list()
    for path in ilist:
        if os.path.isfile(path):
            wikiname = quote(path, safe="")
            filelist.append((path, wikiname))
        else:
            for root, dirs, files in os.walk(path):
                for file in files:
                    filename = os.path.join(root, file)
                    wikiname = filename[len(os.path.dirname(path)):].lstrip("/")
                    wikiname = quote(wikiname, safe="")
                    filelist.append((filename, wikiname))
        total = len(filelist)
        n = 1
        for filename, wikiname in filelist:
            sys.stdout.write("%d/%d uploading %s as %s\n" % (n, total, filename, wikiname)) 
            uploadFile(collab, page, wikiname, filename)
            n += 1 

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print "Script interrupted via CTRL-C."

