#!/bin/env python
# -*- coding: utf-8 -*-
"""
    @copyright: 2008 by Joachim Viide, Pekka Pietikäinen, Mika Seppänen  
    @license: MIT <http://www.opensource.org/licenses/mit-license.php>
"""
from opencollab.wiki import CLIWiki
from opencollab.meta import Meta

import os
import sys
import optparse

from urllib import quote

def main():

    parser = optparse.OptionParser()
    parser.add_option("-o", "--output",
                      dest="output",
                      default=None,
                      metavar="OUTPUT",
                      help="save the file to name OUTPUT in the wiki")
    parser.add_option("-r", "--recursive",
                      action="store_true",
                      dest="recursive",
                      help="recursivly upload files")

    parser.set_usage("%prog [options] WIKIURL PAGENAME FILENAME")

    options, args = parser.parse_args()
    if len(args) != 3:
        parser.error("wiki url, pagename and filename have to be defined")

    url, page, path = args

    wiki = CLIWiki(url)

    if options.recursive:
        filelist = list()

        for root, dirs, files in os.walk(path):
            for file in files:
                filename = os.path.join(root, file)
                wikiname = filename[len(os.path.dirname(path)):].lstrip("/")
                wikiname = quote(wikiname, safe="")
                filelist.append((filename, wikiname))

        total = len(filelist)
        n = 1
        for filename, wikiname in filelist:
            sys.stdout.write("%d/%d uploading %s as %s\n" % (n, total, filename, wikiname)) 
            uploadFile(wiki, page, wikiname, filename)
            n += 1 

        sys.exit()

    if options.output is None:
        _, filename = os.path.split(path)
    else:
        filename = options.output

    sys.stdout.write("uploading %s as %s\n" % (path, filename)) 
    sys.stdout.flush()
    uploadFile(wiki, page, filename, path)

def uploadFile(wiki, page, filename, path):
    file = open(path, "rb")

    for current, total in wiki.putAttachmentChunked(page, filename, file):
        percent = 100.0 * current / float(max(total, 1))
        status = current, total, percent

        sys.stdout.write("\rsent %d/%d bytes (%.02f%%) " % status)
        sys.stdout.flush()

    sys.stdout.write("done\n")
    sys.stdout.flush()

    file.close()

if __name__ == "__main__":
    main()
