#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
    @copyright: 2008 Lari Huttunen
    @license: MIT <http://www.opensource.org/licenses/mit-license.php>
"""
import re
import optparse
import getpass
import imaplib
import email
import email.utils
from email.Iterators import body_line_iterator
from opencollab.util.config import parse_config
from opencollab.wiki import CLIWiki
from opencollab.meta import Metas, Meta, Func
from opencollab.util.regexp import *

def import_identities(collab,collab_metas,template,verbose):
    for page,pmeta in collab_metas.iteritems():
        if page:
            status = collab.setMeta(page,pmeta,template=template,replace=True)
    if verbose:
        print status

def read_spam(imaps_server,imaps_user,imaps_pass):
    href = re.compile('\w+=\"')
    tag = re.compile('\">?.*$')
    mailbox = imaplib.IMAP4_SSL(imaps_server) 
    if imaps_pass is None:
        mailbox.login(imaps_user,getpass.getpass())
    else:
        mailbox.login(imaps_user,imaps_pass)
    mailbox.select()
    typ, data = mailbox.search(None, 'NEW')
    for num in data[0].split():
        typ, data = mailbox.fetch(num, '(RFC822)')
        msg = email.message_from_string(data[0][1])
        body = ""
        for line in body_line_iterator(msg, decode=True):
                body+=line
        tokens = body.split()
        for token in tokens:
            if url_all_re.search(token):
                token = href.sub('', token)
                token = tag.sub('', token)
                print token
            
    mailbox.close()
    mailbox.logout()

def main():
    parser = optparse.OptionParser()
    parser.add_option( "-c", "--config",
        action="store",
        type="string", dest="config",
        metavar="CONFIG",
        help="CONFIG  file path.")
    parser.add_option( "-i", "--imaps-server",
        action="store",
        type="string", dest="imaps_server",
        metavar="IMAPS-SERVER",
        help="IMAPS-SERVER name or IP address.")
    parser.add_option( "-t", "--wiki-template",
        action="store",
        type="string", dest="wiki_template",
        metavar="TEMPLATE",
        help="Wiki TEMPLATE.")
    parser.add_option( "-u", "--user",
        action="store",
        type="string", dest="imaps_user",
        metavar="IMAPS-USERNAME",
        help="IMAPS-USERNAME.")
    parser.add_option("-v",
        action="store_true", dest="verbose", default=False,
        help="Enable verbose output." )
    parser.set_usage("%prog [options] COLLABURL")
    options, args = parser.parse_args()
    iopts={}
    if options.config:
        iopts = parse_config(options.config, "creds", "spam")
        if "url" in iopts["creds"]:
            url = iopts["creds"]["url"]
            collab = CLIWiki(url, config=options.config)
        else:
            error = "COLLABURL needs to be specified."
            sys.exit(error)
    elif len(args) != 1:
        parser.error("Collab URL has to be specified.")
    else:
        url=args[0]
        collab = CLIWiki(url)
    if options.imaps_server:
        imaps_server = options.imaps_server
    elif options.config and "imaps_server" in iopts["spam"]:
        imaps_server = iopts["spam"]["imaps-server"]
    else:
        imaps_server = None
    if options.imaps_user:
        imaps_user = options.imaps_user
    elif options.config and "imaps-user" in iopts["spam"]:
        imaps_server = iopts["spam"]["imaps-user"]
    else:
        imaps_user = None
    if options.config and "imaps-pass" in iopts["spam"]:
        imaps_pass = iopts["spam"]["imaps-pass"]
    else:
        imaps_pass = None
    if options.wiki_template:
        wiki_template = options.wiki_template
    elif options.config and "wiki-template" in iopts["spam"]:
        wiki_template = iopts["spam"]["wiki-template"]
    else:
        wiki_template = "SpamTemplate"
    collab_metas = Metas()
    if options.verbose:
        print "Reading new spam messages from:", imaps_server, imaps_user, "INBOX"
    if imaps_server is not None and imaps_user is not None:
        read_spam(imaps_server,imaps_user,imaps_pass)
    else:
        sys.exit("You need to specify IMAPS-SERVER and IMAPS-USER.")
    import_identities(collab,collab_metas,wiki_template)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print "Script interrupted via CTRL-C."
