#! /usr/bin/env python
# -*- coding: utf-8 -*-
"""
    @copyright: 2008 by Jani Kenttälä
    @license: MIT <http://www.opensource.org/licenses/mit-license.php>
"""
import os,sys,re,optparse,socket
from opencollab.wiki import CLIWiki, WikiFailure
from opencollab.util.config import parseOptions
from urllib import quote

def main():
    parser = optparse.OptionParser()
    parser.add_option( "-s", "--search-string",
        action="store", type="string", dest="search", default=None,
        metavar = "SEARCH-STRING", help="SEARCH-STRING for getMeta().")
    parser.add_option("-n", "--dry-run",
        dest="dryrun", action="store_true",
        default=False, help="Show what would have been deleted.")
    ops = {}
    sect = "delete"
    ops = parseOptions(parser, sect)
    url = ops["creds"]["url"]
    verbose = ops[sect]["verbose"]
    dryrun = ops[sect]["dryrun"]
    search_string = ops[sect]["search"]
    if search_string is None:
        parser.error("Search string needs to be specified. Use -h for help.")
    if verbose:
        print "Authenticating to: " + repr(url)
    while True:
        try:
            collab = CLIWiki(**ops['creds'])
        except WikiFailure:
            print "ERROR: Authentication failed."
        except (UnicodeError, socket.gaierror):
            sys.exit("ERROR: Not a valid URL.")
        else:
            break
    columns = re.compile('\|\|.*\|\|')
    if not columns.findall(search_string):
        search_string += ",||||"
    metas = collab.getMeta(search_string)
    for page in metas:
        print "Deleting %r..." % (page),
        if not dryrun:
            try:
                collab.deletePage(page)
                print "[ok].",
            except WikiFailure, (strerror):
                print "[failed]: %s"  % (strerror),
        print
    print

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print "Script interrupted via CTRL-C."

