#! /usr/bin/env python
# -*- coding: utf-8 -*-
"""
    @copyright: 2008 Lari Huttunen
    @license: MIT <http://www.opensource.org/licenses/mit-license.php>
"""

import os
import sys
import re

from opencollab.meta import Meta, Metas
from opencollab.wiki import CLIWiki, WikiFailure

def get_page_html(collab, page):
    content = ""
    try:
        content = collab.getPageHTML(page)
    except WikiFailure, msg:
        print "WikiFailure: ", msg
    else:
        print content

def main():
    import optparse

    parser = optparse.OptionParser()
    parser.add_option("-c", "--config",
                      dest="config",
                      default=None,
                      metavar="CONFIG",
                      help=("Read configurable variables from CONFIG."))
    options, args = parser.parse_args()

    url = ''
    arg = 'CategoryCodenomiconArena'
    if args:
        url = args[0]
    collab = CLIWiki(url, config=options.config)
    pages = Metas() 
    pages = collab.getMeta(arg)
    for page in pages:
        get_page_html(collab, page)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print "Script interrupted via CTRL-C."

