#! /usr/bin/env python
# -*- coding: utf-8 -*-
"""
    @copyright: 2008 by Joachim Viide
    @license: MIT <http://www.opensource.org/licenses/mit-license.php>
"""

import os
import sys
import time
import socket
import signal
import pickle
import random
import select

from opencollab.meta import Meta
from opencollab.wiki import CLIWiki, WikiFailure

def processIsAlive(processId):
    try:
        pid, status = os.waitpid(processId, os.WNOHANG)
    except os.error:
        return False
    return pid != processId

def execute(page, script, keys):
    locals = dict()

    exec script in locals

    func = locals.get("execute")
    return func(page, **keys)

def readData(*fds):
    datas = list()
    readable, _, _ = select.select(fds, [], [], 0)

    for index, fd in enumerate(fds):
        if fd in readable:
            datas.append(os.read(fd, 1024**2))
        else:
            datas.append("")

    return datas

def runOneTask(agentId, wiki, interval=10.0, dieAfter=10*60.0):
    while True:
        print "Fetching a new task"
        newTask = wiki.request("TaskServer", agentId, "get")
        if newTask:
            break

        print "No new task found"
        time.sleep(interval)

    page, metas, lang, script = newTask
    print "Got task '%s'" % page
    print " lang: %s" % lang
    print " metas: %s" % repr(metas)

    resultReadFd, resultWriteFd = os.pipe()
    outReadFd, outWriteFd = os.pipe()
    errReadFd, errWriteFd = os.pipe()

    pid = os.fork()
    if pid == 0:
        os.close(resultReadFd)
        os.close(outReadFd)
        os.close(errReadFd)

        # Redirect stdout
        os.dup2(outWriteFd, 1)
        os.close(outWriteFd)

        # Redirect stderr
        os.dup2(errWriteFd, 2)
        os.close(errWriteFd)

        result = execute(page, script, metas)
        os.write(resultWriteFd, pickle.dumps(result))

        os.close(resultWriteFd)
        os._exit(0)

    os.close(outWriteFd)
    os.close(errWriteFd)
    os.close(resultWriteFd)

    outData = ""
    errData = ""
    pollInterval = 0.1
    lastHeartBeat = checkpoint = time.time()
    while True:
        newOutData, newErrData = readData(outReadFd, errReadFd)

        sys.stdout.write(newOutData)
        sys.stdout.flush()
        outData += newOutData

        sys.stderr.write(newErrData)
        sys.stderr.flush()
        errData += newErrData

        if not processIsAlive(pid):
            reader = os.fdopen(resultReadFd, "rb")
            data = reader.read()
            reader.close()

            try:
                result = pickle.loads(data)
            except EOFError:
                wiki.request("TaskServer", agentId, "change", page,
                             dict(status=["failed"]))
                print "Task failed"
            else:
                print "Got result %s" % repr(result)
                wiki.request("TaskServer", agentId, "close", page, result)
                print "Sent result"

            break

        if time.time()-lastHeartBeat >= interval:
            socket.setdefaulttimeout(2 * interval)
            try:
                try:
                    print " ...heartbeat..."
                    wiki.request("TaskServer", agentId, "change", page)
                except WikiFailure, failure:
                    print failure
                else:
                    checkpoint = time.time()
            finally:
                socket.setdefaulttimeout(None)
            lastHeartBeat = time.time()

        if time.time()-checkpoint >= dieAfter:
            os.kill(pid, signal.SIGINT)
            while processIsAlive(pid):
                time.sleep(pollInterval)
            return

        time.sleep(pollInterval)

def main():
    import optparse

    parser = optparse.OptionParser()
    parser.add_option("-n", "--name",
                      dest="name",
                      default=None,
                      metavar="NAME",
                      help="force the agent's name to NAME")
    parser.add_option("-c", "--config",
                      dest="config",
                      default=None,
                      metavar="CONFIG",
                      help=("read the username and password from the "+
                            "config file CONFIG"))
    options, args = parser.parse_args()

    url = ''
    if args:
        url = args[0]
    wiki = CLIWiki(url, config=options.config)

    name = options.name
    if name is None:
        name = socket.gethostbyname(socket.gethostname())
    name += "-%d" % random.randint(0, 2**32)

    print "Getting tasks from %s as agent %s" % (url, name)

    while True:
        runOneTask(name, wiki)

if __name__ == "__main__":
    main()
