#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@copyright: 2015 Ossi Herrala
@license: MIT <http://www.opensource.org/licenses/mit-license.php>

@summary: Generate aliases(5) style file from collab groups and users
"""

import sys
import re

from collabbackend.clitools import CollabRequest, listAllCollabs
from graphingwiki.groups import users_by_group

# A bit more strict regex for group matching
# Group name must be valid user part for email address.
GROUP_RE = re.compile(r'^([A-Za-z0-9-]+)Group$')


def _group_name(group):
    try:
        g = GROUP_RE.match(group).group(1)
        return g.lower()
    except AttributeError:
        return None


def main():
    for collab in listAllCollabs():
        with CollabRequest(collab) as request:
            for group in request.request.groups:
                group_name = _group_name(group)
                if not group_name:
                    # Invalid group name. do no work with it.
                    continue

                emailto = set()
                for user in users_by_group(request.request, group,
                                           recursive=True):
                    if request.getUser(user).exists():
                        emailto.add(user)

                if len(emailto) > 0:
                    print "{0}-{1}: {2}".format(collab, group_name,
                                                ", ".join(emailto))


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(1)
