#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
collab-htaccess: Filesystem dump of collab instance meta / htpasswd / htaccess

@copyright: 2008-2010 by Marko Laakso <fenris@iki.fi>
@license: MIT <http://www.opensource.org/licenses/mit-license.php>
"""

import os
import sys
import re
import difflib
import string
import signal
import atexit
import time

def cleanup_handler(signum, frame):
    sys.exit(0)

def delpid():
    try:
        os.remove(mypidfile)
    except OSError:
        pass

import posix, pwd

import getopt

try:
    opts, args = getopt.getopt(sys.argv[1:], "vn")
except getopt.GetoptError:
    print __file__ + " [-v(erbose)] [-n(oop)]"
    sys.exit(2)

verbose = False
noop = False

for opt, arg in opts:
    if opt == '-v':
        verbose = True
    elif opt == '-n':
        noop = True

import ConfigParser

config = ConfigParser.RawConfigParser()
config.read('/etc/local/collab/collab.ini')

mylogconf = config.get('collab', 'logconf')
mybaseinstancedir = config.get('collab', 'baseinstancedir')
myhtpasswd = config.get('collab', 'htpasswd')
myhtgroup = config.get('collab', 'htgroup')
myhtmldir = config.get('collab', 'htmldir')
mywikidir = config.get('collab', 'wikidir')
mypiddir = config.get('collab', 'piddir')

mypidfile = os.path.join(mypiddir, "collab-htaccess.pid")

try:
    f = file(mypidfile, 'r')
    pid = int(f.read().strip())
    statinfo = os.fstat(f.fileno())
    pidage = time.time() - statinfo.st_ctime
    f.close()

    if pidage > 60 * 15:
        print "Walking over pid=%d with age=%d (secs) in pidfile=%s" \
              % (pid, pidage, mypidfile)
    else:
        sys.exit(1)
except IOError:
    pid = None

signal.signal(signal.SIGTERM, cleanup_handler)
atexit.register(delpid)

pid = str(os.getpid())
f = open(mypidfile, 'w+')
f.write(pid + '\n')
f.close()

from MoinMoin import log
log.load_config(mylogconf)

# We need to import contexts before importing users, because otherwise
# the relative imports in MoinMoin will fail.
import MoinMoin.web.contexts
from MoinMoin.user import User, getUserList, isValidName
from MoinMoin.config import multiconfig

from graphingwiki.editing import metatable_parseargs, get_metas
from graphingwiki import RequestCLI

def diffandstore(filename, newtext, dryrun=noop):

    msg = []

    try:
        f = open(filename, 'r')
        oldtext = f.read()
        f.close()
    except IOError:
        oldtext = ''

    newtext = newtext.encode('utf-8')

    if oldtext != newtext:
        diff = difflib.ndiff(oldtext.splitlines(1), newtext.splitlines(1))
        for line in diff:
            if line[:1] not in string.whitespace:
                # Remove password hashes from diff message
                msg.append(re.sub(r'(:{[A-Z]+}).*', r'\1...', line))
        if not dryrun:
            if newtext:
                f = open(filename, 'w')
                f.write(newtext)
                f.close()
            elif os.path.isfile(filename):
                os.remove(filename)

    return msg

###### htgroup

content = "dummygroup: dummyuser"
msg = diffandstore(myhtgroup, content)

if msg:
    print "Access DIFF for .htgroup:"
    sys.stdout.writelines(msg)

###### htpasswd

allusers = { }

os.chdir(mybaseinstancedir)
sys.path.insert(0, os.path.join(mybaseinstancedir, 'config'))

# Make a new request for the page
req = RequestCLI('FrontPage', parse=False)

# Auth
import posix, pwd
req.user = User(req, auth_username=pwd.getpwuid(posix.getuid())[0])

content = ""

for id in getUserList(req):
    myuser = User(req, id=id)
    myuser.load_from_id()
    if myuser.valid and isValidName(req, myuser.name) and myuser.enc_password:
        content = content + myuser.name + ":" + \
                  myuser.enc_password + os.linesep
        allusers[myuser.name] = 0

msg = diffandstore(myhtpasswd, content)

if msg:
    print "Access DIFF for .htpasswd:"
    sys.stdout.writelines(msg)

req.finish()

sys.path.remove(os.path.join(mybaseinstancedir, 'config'))

###### htaccess & CollabFacts

os.chdir(myhtmldir)
username = pwd.getpwuid(posix.getuid())[0]

for dent in os.listdir("."):
    mydata = os.path.join(mywikidir, dent)
    mytemplate = os.path.join(mydata, 'collab-htaccess-template')
    myhtaccess = os.path.join(dent, '.htaccess')
    myfacts = {
        'name': os.path.join(dent, '.title'),
        'description': os.path.join(dent, '.motd'),
        'URL': os.path.join(dent, '.url'),
        'contact': os.path.join(dent, '.contact'),
        'publish': os.path.join(dent, '.publish'),
    }

    if not os.path.isdir(dent) or not os.path.isdir(mydata):
        continue

    if not os.path.isfile(mytemplate):
        continue

    sys.path.insert(0, os.path.join(mydata, 'config'))

    multiconfig._url_re_cache = None
    multiconfig._farmconfig_mtime = None
    multiconfig._config_cache = {}

    import farmconfig
    reload(farmconfig)

    req = RequestCLI('AccessGroup', parse=False)
    req.user = User(req, auth_username=username)

    msg = []
    members = []

    isgroup = req.cfg.cache.page_group_regexact.search

    for member in req.groups.get("AccessGroup"):
        if isgroup(member):
            continue
        if re.search('[^\w@.\-\']', member, re.U) is not None:
            if verbose:
                print >> sys.stderr, "INVALID: " + member + " in " + dent
            continue
        members.append('require user ' + member)
        if member in allusers:
            allusers[member] += 1
        elif verbose:
            print >> sys.stderr, "PHANTOM: " + member + " in " + dent

    members.sort()

    f = open(mytemplate, 'r')
    newtext = f.read()
    f.close()

    for member in members:
        newtext = newtext + member + '\n'

    msg.extend(diffandstore(myhtaccess, newtext))

    allow_publish = getattr(req.cfg, 'collab_allow_publish', False)
    metas = get_metas(req, 'CollabFacts', myfacts.keys())

    for key in myfacts:
        val = ''
        if key == 'publish':
            if allow_publish and metas[key] and metas[key][0].lower() == 'yes':
                val = 'publish\n'
        elif metas[key]:
            val = metas[key][0] + '\n'
        msg.extend(diffandstore(myfacts[key], val))

    if msg:
        print '*** ' + dent + ' ***'
        sys.stdout.writelines(msg)

    req.finish()

    sys.path.remove(os.path.join(mydata, 'config'))

if verbose:
    for user in allusers:
        if allusers[user] == 0:
            u = User(req, None, user)
            userfile = u.getFilename()
            print >> sys.stderr, "rm " + userfile + " # ORPHAN: " + user
