#!/bin/bash
# -*- coding: utf-8 -*-

##  @copyright: 2009-2010 by Marko Laakso
##  @license: MIT <http://www.opensource.org/licenses/mit-license.php>

umask 007

myerr() {

  echo $@ 1>&2
  exit 1
}

CFG=/etc/local/collab/collab.ini

if [ -f ${CFG} ]; then
  . ${CFG} 2> /dev/null
else
  myerr "No ${CFG}"
fi

if [ "blah$1" = "blah-h" ]; then
  shift
fi

if [ "blah$1" = "blah-f" ]; then
  FORCE_EMAIL=yes
  shift
fi

if [ "blah$1" = "blah-r" ]; then
  RANDOMIZE_PASSWORD=yes
  shift
fi

if [ $# -ne 1 ]; then
  echo "Usage: $0 [-f(orce username without @)] [-r(andomize password)] <username>" 1>&2
  exit 1
fi

NAME=$1

if [ "blah${FORCE_EMAIL}" != "blahyes" ]; then
    echo ${NAME} | grep -q '@' || myerr "please use email address with '@'"
fi

if [ "blah${RANDOMIZE_PASSWORD}" = "blahyes" ]; then
  PASSWORD=`dd bs=1 count=32 if=/dev/urandom 2> /dev/null | openssl base64 -e`
  echo "Password: ${PASSWORD}"
else
  read -s -p "Password: " PASSWORD
fi

echo
echo "Creating ${NAME}"
moin --config-dir=${baseinstancedir}/config account create --name ${NAME} --email ${NAME} --password ${PASSWORD}
echo "done"