#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
Dump Apache htpasswd file out of Wiki's users.

@copyright: 2006 by Juhani Eronen <exec@iki.fi>
@copyright: 2008 by Marko Laakso <fenris@iki.fi>
@license: MIT <http://www.opensource.org/licenses/mit-license.php>
"""

import os
import sys

import difflib
import string

def diffandstore(filename, newtext):

    msg = []

    try:
        f = open(filename, 'r')
        oldtext = f.read()
        f.close()
    except IOError:
        oldtext = ''

    newtext = newtext.encode('iso8859-15')
    
    if oldtext != newtext:
        diff = difflib.ndiff(oldtext.splitlines(1), newtext.splitlines(1))
        for line in diff:
            if line[:1] not in string.whitespace:
                msg.append(line)
        f = open(filename, 'w')
        f.write(newtext)
        f.close()

    return msg

######

import ConfigParser

config = ConfigParser.RawConfigParser()
config.read('/etc/local/collab/collab.ini')

mylogconf = config.get('collab', 'logconf')
mybaseinstancedir = config.get('collab', 'baseinstancedir')
myhtpasswd = config.get('collab', 'htpasswd')

from MoinMoin import log
log.load_config(mylogconf) 

os.chdir(mybaseinstancedir)
sys.path.insert(0, os.path.join(mybaseinstancedir, 'config'))

# Make a new request for the page
from MoinMoin.request.request_cli import Request
req = Request(pagename='FrontPage')

from MoinMoin.user import User, getUserList, isValidName

# Auth
import posix, pwd
req.user = User(req, auth_username=pwd.getpwuid(posix.getuid())[0])

content = ""

for id in getUserList(req):
    myuser = User(req, id=id)
    myuser.load_from_id()
    if myuser.valid and isValidName(req, myuser.name) and myuser.enc_password:
        content = content + myuser.name + ":" + \
                  myuser.enc_password + os.linesep

msg = diffandstore(myhtpasswd, content)

if msg:
    print "Access DIFF for .htpasswd:"
    sys.stdout.writelines(msg)
