#!/bin/bash
# -*- coding: utf-8 -*-

##  @copyright: 2009-2010 by Marko Laakso
##  @license: MIT <http://www.opensource.org/licenses/mit-license.php>

umask 007

myerr() {
  echo $@ 1>&2
  exit 1
}

if [ `id -u` = 0 ]; then
    myerr "ERROR: $0: Don't run command as root"
fi

CFG=/etc/local/collab/collab.ini

if [ -f ${CFG} ]; then
  . ${CFG} 2> /dev/null
else
  myerr "No ${CFG}"
fi

if [ "blah$1" = "blah-r" ]; then
  PASSWORD=`tr -dc '[:alpha:]' < /dev/urandom | head -c 32`
  shift
fi

if [ $# -ne 1 ]; then
  echo "Usage: $0 <username>" 1>&2
  exit 1
fi

NAME=$1

echo "${NAME}" | grep -q '@' || echo "No '@' in username, email might not work!"

if [ "blah${PASSWORD}" = "blah" ]; then
  read -s -p "Password: " PASSWORD
else
  echo "Password: $PASSWORD"
fi

echo
echo "Changing password for ${NAME}"
moin --config-dir=${baseinstancedir}/config account resetpw --name "${NAME}" "${PASSWORD}"
echo "done"

echo "Checking ${NAME}, both email and name should be shown here (TWO lines)..."

grep "${NAME}" ${userdir}/*

echo "You should fix email= in that file if it is not there..."
