#!/bin/sh
# -*- coding: utf-8 -*-

##  @copyright: 2009-2010 by Jani Kenttälä, Marko Laakso
##  @license: MIT <http://www.opensource.org/licenses/mit-license.php>

myerr() {
  echo $@ 2>&1
  exit 1
}

CFG=/etc/local/collab/collab.ini

if [ -f ${CFG} ]; then
  . ${CFG} 2> /dev/null
else
  myerr "No ${CFG}"
fi

if [ $# -ne 1 ]; then
  myerr "Usage: $0 <username>"
fi

MYUSER=$1

grep -H ${MYUSER} ${htmldir}/*/.htaccess | sed -e 's/:/ /' | \
  while read p r u a; do
    d=`dirname $p` 
    printf "%s %s\n" `basename $d` $a
  done
