#! /usr/bin/env python
# -*- coding: utf-8 -*-
"""
    raippa-install
     - Installs the Raippa plugins to a wiki.

    @copyright: 2006 by Juhani Eronen <exec@iki.fi>
    @license: MIT <http://www.opensource.org/licenses/mit-license.php>

    Permission is hereby granted, free of charge, to any person
    obtaining a copy of this software and associated documentation
    files (the "Software"), to deal in the Software without
    restriction, including without limitation the rights to use, copy,
    modify, merge, publish, distribute, sublicense, and/or sell copies
    of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
    NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
    HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
    WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.

"""

import os
import sys
from shutil import copyfile

from optparse import OptionParser

usage = "usage: %prog [options] dst"
parser = OptionParser(usage=usage)
parser.add_option("-v", "--verbose", action="store_true", dest="verbose",
                  help="Report success")

(options, args) = parser.parse_args()

try:
    import raippa 
except ImportError:
    sys.stderr.write("Cannot find raippa, exiting...\n")
    sys.exit(1)

if len(args) != 1:
    parser.print_help()
    sys.exit(1)
 
destdir = os.path.join(args[0], 'data/plugin')
if not os.path.isdir(destdir):
    sys.stderr.write("Path %s doesn't exists or it isn't directory.\n" % destdir)
    sys.exit(1)

def copytree(src, dst, symlinks=False):
    """ Modified from shutil to allow existing directories
    """
    names = os.listdir(src)
    if not os.path.isdir(dst):
        os.mkdir(dst)
    errors = []
    for name in names:
        srcname = os.path.join(src, name)
        dstname = os.path.join(dst, name)
        if options.verbose:
            print "Copying %s to %s" % (srcname, dstname)
        try:
            if symlinks and os.path.islink(srcname):
                linkto = os.readlink(srcname)
                os.symlink(linkto, dstname)
            elif os.path.isdir(srcname):
                copytree(srcname, dstname, symlinks)
            else:
                copyfile(srcname, dstname)
            # XXX What about devices, sockets etc.?
        except (IOError, os.error), why:
            errors.append((srcname, dstname, str(why)))
    if errors:
        for src, dst, why in errors:
            print "copy from %s to %s failed: %s" % (src, dst, why)
        sys.exit("raippa-install failed.")

# Get pkg path
pkgdir = os.path.join(os.path.dirname(os.path.abspath(raippa.__file__)),
                      'plugin')

copytree(pkgdir, destdir)

