#!/usr/bin/env bash

set -e

repobase=https://bitbucket.org/clarifiednetworks/graphingwiki

function usage {

    cat <<EOF 1>&2
usage: get-gwiki-tgz [branch-name or tag-name or changeset-id]'

Default branch-name is "tip" (the head of the repository).
See ${repobase}/ for alternatives.
EOF
    exit 1
}

if [ "blah$1" = "blah-h" -o "blah$1" = "blah--help" ]; then
   usage
fi

if [ "$#" = 0 ]; then
   branch=default
elif [ "$#" = 1 ]; then
   branch=${1}
else
   usage
fi

if [ -x /usr/bin/curl ]; then
  GETTER=/usr/bin/curl
  GETTEROPTS="-O"
else
  GETTER=wget
  GETTEROPTS=
fi

version=`date +"%Y%m%d-%H%M"`
package=${branch}.tar.gz
packageversioned=graphingwiki-${branch}-${version}.tgz
url=$repobase/get/${package}

d=`mktemp -d /tmp/gwiki-get-tgz.XXXXX`
trap "echo deleting temp dir >&2; rm -rf -fr $d" 0

(
  cd ${d}
  ${GETTER} ${GETTEROPTS} ${url}
)

if [ ! -f ${d}/${package} ]; then
  echo "Failed to get ${package} from ${url}" 1>&2
  exit 1
fi

mv ${d}/${package} ${packageversioned}
echo "Got: ${packageversioned}"