#!/usr/bin/env bash
set -e

function usage {
    echo usage: get-gwiki-tgz '<revision>' '[branch]'
    echo "To see latest revision, use svn info '$repobase'. If branch is omitted, trunk is assumed."
    exit 1
}

repobase=http://svn.graphingwiki.python-hosting.com

if [ "$1" = "-h" ]; then
   usage
fi

if [ "$#" = 1 ]; then
   repobase=$repobase/trunk
   branch_id=trunk
elif [ "$#" = 2 ]; then
   repobase=$repobase/branches/$2
   branch_id=$2
else
   usage
fi



d=`mktemp -d /tmp/gwiki-get-tgz.XXXXX`
trap "echo deleting temp dir >&2; rm -rf -fr $d" 0
pkgname=graphingwiki-$branch_id-$1
svn co -r $1 $repobase $d/$pkgname || exit 1
tar -C $d -czf $pkgname.tgz $pkgname

