#! /usr/bin/env python
# -*- coding: utf-8 -*-
"""
    gwiki-showgraph
     - Debug: A CLI interface to the ShowGraph action.

    @copyright: 2006 by Juhani Eronen <exec@iki.fi>
    @license: MIT <http://www.opensource.org/licenses/mit-license.php>

    Permission is hereby granted, free of charge, to any person
    obtaining a copy of this software and associated documentation
    files (the "Software"), to deal in the Software without
    restriction, including without limitation the rights to use, copy,
    modify, merge, publish, distribute, sublicense, and/or sell copies
    of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
    NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
    HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
    WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.

"""

import sys, os

try:
    wikipath = sys.argv[2]
    os.chdir(wikipath)
except:
    print "Usage: " + sys.argv[0] + " <pagename> <path-to-wiki>\n" 
    raise

# Moin dirs
sys.path.insert(0, os.path.join(wikipath, 'config'))
from MoinMoin import wikiutil
from MoinMoin.Page import Page
from MoinMoin.support.werkzeug.datastructures import CombinedMultiDict, \
    MultiDict

pagename = sys.argv[1]

from graphingwiki import RequestCLI
# Make a new request for the page, get raw text
req = RequestCLI(pagename=pagename, parse=False)

form = dict()
form['action'] = ['ShowGraph']
form['colorby'] = ['Status']
form['orderby'] = ['Year']
request.values = CombinedMultiDict([MultiDict(form)])

p = Page(req, pagename)
pagedir = p.getPagePath()
text = p.get_raw_body()

# Apply the showgraph-action to the page
showgraph = wikiutil.importPlugin(req.cfg, 'action', 'ShowGraph')
showgraph(pagename, req)
