#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys, os
sys.path.append(os.path.join(os.path.split(os.path.abspath(__file__))[0], '..', 'lib', 'python%d.%d' % sys.version_info[:2], 'site-packages'))
from optparse import OptionParser
from graphingwiki.editing import savetext

if __name__ == '__main__':
    usage = "usage: %prog <path to wiki> <pagename>"
    parser = OptionParser(usage=usage)
    parser.add_option("-v", "--verbose", action="store_true", dest="verbose",
                      help="Report success")

    (options, args) = parser.parse_args()

    if len(args) != 2:
        print parser.get_usage()
        sys.exit(2)

    # Configdir to path, so wikiconfig can be imported by Request
    try:
        configdir = os.path.join(args[0], 'config')
        sys.path.append(configdir)
    except:
        configdir = args[0]
        sys.path.append(configdir)

    pagename = args[1]

    mytext = unicode(sys.stdin.read(), sys.getfilesystemencoding())
    savetext(pagename, mytext)
