#! /usr/bin/env python
# -*- coding: utf-8 -*-
"""
    gwiki-debuggraph
     - Debug: Shows a page's graph data in list and dot formats.
       Pagename given in sys.argv[1].

    @copyright: 2006 by Juhani Eronen <exec@iki.fi>
    @license: MIT <http://www.opensource.org/licenses/mit-license.php>

    Permission is hereby granted, free of charge, to any person
    obtaining a copy of this software and associated documentation
    files (the "Software"), to deal in the Software without
    restriction, including without limitation the rights to use, copy,
    modify, merge, publish, distribute, sublicense, and/or sell copies
    of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
    NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
    HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
    WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.

"""

import sys, os
sys.path.append(os.path.join(os.path.split(os.path.abspath(__file__))[0], '..', 'lib', 'python%d.%d' % sys.version_info[:2], 'site-packages'))

import cPickle

from graphingwiki.graphrepr import GraphRepr
from MoinMoin.wikiutil import quoteWikinameFS

try:
    wikipath = sys.argv[2]
    page = quoteWikinameFS(unicode(sys.argv[1], sys.getfilesystemencoding()))
    filepath = os.path.join(wikipath, 'data/pages', page, "graphdata.pickle")
    print filepath
except:
    print "Usage: " + sys.argv[0] + " <pagename> <path-to-wiki>\n" 
    raise

f = file(filepath)
g = cPickle.load(f)

for i in g.nodes.getall():
    print i[0]
    print [(x, getattr(g.nodes.get(*i), x)) for x in dict(g.nodes.get(*i))]

for i in g.edges.getall():
    print i
    print dict(g.edges.get(*i))

gr = GraphRepr(g, engine='neato')
gr.graphviz.set(overlap='false')
g.commit()

from tempfile import mkstemp
no, name = mkstemp()
gr.graphviz.layout(file=name)
f = file(name)
print f.read()
