#! /usr/bin/env python
# -*- coding: iso-8859-1 -*-
"""
    gwiki-xml-meta
     - Edits or lists metadata from pages

    @copyright: 2007 by Juhani Eronen <exec@iki.fi> and Joachim Viide
    @license: MIT <http://www.opensource.org/licenses/mit-license.php>
"""

import sys
import getpass
import csv

from optparse import OptionParser
from urllib import unquote as url_unquote

from graphingwiki.patterns import qstrip_p, encode
from graphingwiki.editing import xmlrpc_error, xmlrpc_conninit, xmlrpc_connect

usage = "usage: %prog [options] wikiurl"
parser = OptionParser(usage=usage)

parser.add_option("-g", "--get", dest="get_args", action='append', default=[],
                  help="Get metadata from page or page regexp")
parser.add_option("-k", "--key", dest="key_args", action='append',
                  help="Get only specified keys")
parser.add_option("-m", "--match", dest="match_args", action='append',
                  help="Get only pages that match arguments")
parser.add_option("-K", "--keys", action="store_true", dest="keysonly",
                  default=False, help="Get only metadata keys, not values")
parser.add_option("-a", "--append", dest="app_args",
                  help="Get metadata to page")
parser.add_option("-r", "--replace", dest="repl_args",
                  help="Get metadata to page")

options, args = parser.parse_args()

if len(args) != 1:
    sys.stderr.write("Bad Args\n")
    parser.print_help()
    sys.exit(1)

wiki = args[0]

username = raw_input("Username:")
password = getpass.getpass("Password:")

if options.app_args:
    pass
elif options.repl_args:
    pass
else:
    srcWiki, _ = xmlrpc_conninit(wiki, username, password)
    val = ",".join(options.get_args)
    if options.key_args:
        val += ',||' + '||'.join(options.key_args) + '||'
    if options.match_args:
        val += ',' + ','.join(options.match_args)
        
    result = xmlrpc_connect(srcWiki.GetMeta, wiki, val, options.keysonly)
    wr = csv.writer(sys.stdout)
    if isinstance(result, list):
        if options.keysonly:
            wr.writerow(['Keys'] + [url_unquote(x) for x in result[0]])
            wr.writerow(['Pages'] + [url_unquote(x) for x in result[1]])
        else:
            for row in result:
                wr.writerow([url_unquote(encode(''.join(x))) for x in row])

        sys.exit(0)

# Us being here means that an error has occurred
errno, err = xmlrpc_error(result)
sys.stderr.write("Error %s: %s\n" % (errno, err))
sys.exit(1)
